/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-20 08:10:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1713335927699L));
    _jspx_dependants.put("jar:file:/C:/Users/shaky/OneDrive/Desktop/OOP%20LAB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Buss/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Bus Details</title>\r\n");
      out.write("\r\n");
      out.write("	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("	--poppins: 'Poppins', sans-serif;\r\n");
      out.write("	--lato: 'Lato', sans-serif;\r\n");
      out.write("\r\n");
      out.write("	--light: #F9F9F9;\r\n");
      out.write("	--blue: #3C91E6;\r\n");
      out.write("	--light-blue: #CFE8FF;\r\n");
      out.write("	--grey: #eee;\r\n");
      out.write("	--dark-grey: #AAAAAA;\r\n");
      out.write("	--dark: #342E37;\r\n");
      out.write("	--red: #DB504A;\r\n");
      out.write("	--yellow: #FFCE26;\r\n");
      out.write("	--light-yellow: #FFF2C6;\r\n");
      out.write("	--orange: #FD7238;\r\n");
      out.write("	--light-orange: #FFE0D3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body.dark {\r\n");
      out.write("	--light: #0C0C1E;\r\n");
      out.write("	--grey: #060714;\r\n");
      out.write("	--dark: #FBFBFB;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background: var(--grey);\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write("    display: flex; \r\n");
      out.write("    justify-content: center; \r\n");
      out.write("     max-width: 80%; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".heading {\r\n");
      out.write("    background-color: white; \r\n");
      out.write("    color: blue; \r\n");
      out.write("    font-size: 36px; \r\n");
      out.write("    padding: 10px 40px; \r\n");
      out.write("    border-radius: 10px; \r\n");
      out.write("    margin: 0; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: var(--light);\r\n");
      out.write("	z-index: 2000;\r\n");
      out.write("	font-family: var(--lato);\r\n");
      out.write("	transition: .3s ease;\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("	scrollbar-width: none;\r\n");
      out.write("}\r\n");
      out.write("#sidebar::--webkit-scrollbar {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("#sidebar.hide {\r\n");
      out.write("	width: 60px;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .brand {\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    height: 56px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    color: #007bff; \r\n");
      out.write("    position: sticky;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background: #f8f9fa; \r\n");
      out.write("    z-index: 500;\r\n");
      out.write("    padding: 10px 20px; \r\n");
      out.write("    box-sizing: border-box; \r\n");
      out.write("    border-bottom: 2px solid #007bff; \r\n");
      out.write("}\r\n");
      out.write("#sidebar .brand .bx {\r\n");
      out.write("	min-width: 100px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-top: 48px;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li {\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	margin-left: 6px;\r\n");
      out.write("	border-radius: 48px 0 0 48px;\r\n");
      out.write("	padding: 4px;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li.active {\r\n");
      out.write("	background: var(--grey);\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li.active::before {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	top: -40px;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	box-shadow: 20px 20px 0 var(--grey);\r\n");
      out.write("	z-index: -1;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li.active::after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	bottom: -40px;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	box-shadow: 20px -20px 0 var(--grey);\r\n");
      out.write("	z-index: -1;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li a {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: var(--light);\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	border-radius: 48px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu.top li.active a {\r\n");
      out.write("	color: var(--blue);\r\n");
      out.write("}\r\n");
      out.write("#sidebar.hide .side-menu li a {\r\n");
      out.write("	width: calc(48px - (4px * 2));\r\n");
      out.write("	transition: width .3s ease;\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li a.logout {\r\n");
      out.write("	color: var(--red);\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu.top li a:hover {\r\n");
      out.write("	color: var(--blue);\r\n");
      out.write("}\r\n");
      out.write("#sidebar .side-menu li a .bx {\r\n");
      out.write("	min-width: calc(60px  - ((4px + 6px) * 2));\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("#content {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: calc(100% - 280px);\r\n");
      out.write("	left: 280px;\r\n");
      out.write("	transition: .3s ease;\r\n");
      out.write("}\r\n");
      out.write("#sidebar.hide ~ #content {\r\n");
      out.write("	width: calc(100% - 60px);\r\n");
      out.write("	left: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content nav {\r\n");
      out.write("	height: 56px;\r\n");
      out.write("	background: var(--light);\r\n");
      out.write("	padding: 0 24px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	grid-gap: 24px;\r\n");
      out.write("	font-family: var(--lato);\r\n");
      out.write("	position: sticky;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	z-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("#content nav::before {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	bottom: -40px;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	box-shadow: -20px -20px 0 var(--light);\r\n");
      out.write("}\r\n");
      out.write("#content nav a {\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("}\r\n");
      out.write("#content nav .bx.bx-menu {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("}\r\n");
      out.write("#content nav .nav-link {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	transition: .3s ease;\r\n");
      out.write("}\r\n");
      out.write("#content nav .nav-link:hover {\r\n");
      out.write("	color: var(--blue);\r\n");
      out.write("}\r\n");
      out.write("#content nav form {\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("#content nav form .form-input {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("}\r\n");
      out.write("#content nav form .form-input input {\r\n");
      out.write("	flex-grow: 1;\r\n");
      out.write("	padding: 0 16px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background: var(--grey);\r\n");
      out.write("	border-radius: 36px 0 0 36px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("}\r\n");
      out.write("#content nav form .form-input button {\r\n");
      out.write("	width: 36px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background: var(--blue);\r\n");
      out.write("	color: var(--light);\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	border-radius: 0 36px 36px 0;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("#content nav .notification {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("#content nav .notification .num {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: -6px;\r\n");
      out.write("	right: -6px;\r\n");
      out.write("	width: 20px;\r\n");
      out.write("	height: 20px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	border: 2px solid var(--light);\r\n");
      out.write("	background: var(--red);\r\n");
      out.write("	color: var(--light);\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("#content nav .profile img {\r\n");
      out.write("	width: 36px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("#content nav .switch-mode {\r\n");
      out.write("	display: block;\r\n");
      out.write("	min-width: 50px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	background: var(--grey);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("#content nav .switch-mode::before {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 2px;\r\n");
      out.write("	left: 2px;\r\n");
      out.write("	bottom: 2px;\r\n");
      out.write("	width: calc(25px - 4px);\r\n");
      out.write("	background: var(--blue);\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	transition: all .3s ease;\r\n");
      out.write("}\r\n");
      out.write("#content nav #switch-mode:checked + .switch-mode::before {\r\n");
      out.write("	left: calc(100% - (25px - 4px) - 2px);\r\n");
      out.write("}\r\n");
      out.write("/* MAIN */\r\n");
      out.write("#content main {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 36px 24px;\r\n");
      out.write("	font-family: var(--poppins);\r\n");
      out.write("	max-height: calc(100vh - 56px);\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	grid-gap: 16px;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title .left h1 {\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title .left .breadcrumb {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	grid-gap: 16px;\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title .left .breadcrumb li {\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title .left .breadcrumb li a {\r\n");
      out.write("	color: var(--dark-grey);\r\n");
      out.write("	pointer-events: none;\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title .left .breadcrumb li a.active {\r\n");
      out.write("	color: var(--blue);\r\n");
      out.write("	pointer-events: unset;\r\n");
      out.write("}\r\n");
      out.write("#content main .head-title .btn-download {\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	padding: 0 16px;\r\n");
      out.write("	border-radius: 36px;\r\n");
      out.write("	background: var(--blue);\r\n");
      out.write("	color: var(--light);\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	grid-gap: 10px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content main .box-info {\r\n");
      out.write("	display: grid;\r\n");
      out.write("	grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));\r\n");
      out.write("	grid-gap: 24px;\r\n");
      out.write("	margin-top: 36px;\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li {\r\n");
      out.write("	padding: 24px;\r\n");
      out.write("	background: var(--light);\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	grid-gap: 24px;\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li .bx {\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li:nth-child(1) .bx {\r\n");
      out.write("	background: var(--light-blue);\r\n");
      out.write("	color: var(--blue);\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li:nth-child(2) .bx {\r\n");
      out.write("	background: var(--light-yellow);\r\n");
      out.write("	color: var(--yellow);\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li:nth-child(3) .bx {\r\n");
      out.write("	background: var(--light-orange);\r\n");
      out.write("	color: var(--orange);\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li .text h3 {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("}\r\n");
      out.write("#content main .box-info li .text p {\r\n");
      out.write("	color: var(--dark);	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content main .table-data {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	grid-gap: 24px;\r\n");
      out.write("	margin-top: 24px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	color: var(--dark);\r\n");
      out.write("	float: left;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data > div {\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	background: var(--light);\r\n");
      out.write("	padding: 24px;\r\n");
      out.write("	overflow-x: auto;\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .head {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	grid-gap: 16px;\r\n");
      out.write("	margin-bottom: 24px;\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .head h3 {\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .head .bx {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content main .table-data .order {\r\n");
      out.write("	flex-grow: 1;\r\n");
      out.write("	flex-basis: 500px;\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .order table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	height:70;\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .order table th {\r\n");
      out.write("	padding-bottom: 12px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	border-bottom: 1px solid var(--grey);\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .order table td {\r\n");
      out.write("	padding: 16px 0;\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .order table tr td:first-child {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	grid-gap: 12px;\r\n");
      out.write("	padding-left: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content main .table-data .order table tbody tr:hover {\r\n");
      out.write("	background: var(--grey);\r\n");
      out.write("}\r\n");
      out.write("#content main .table-data .order table tr td .status {\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("	padding: 6px 16px;\r\n");
      out.write("	color: var(--light);\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The popup form - hidden by default */\r\n");
      out.write(".form-popup {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 50px; /* Adjusted from bottom: -20 */\r\n");
      out.write("  left: 350px; /* Changed from right: 15px */\r\n");
      out.write("  border: 3px solid #f1f1f1;\r\n");
      out.write("  z-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add styles to the form container */\r\n");
      out.write(".form-container {\r\n");
      out.write("  max-width: 400px;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write(".form-container input[type=text] {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 5px 0 22px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* When the inputs get focus, do something */\r\n");
      out.write(".form-container input[type=text]:focus {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit/login button */\r\n");
      out.write(".form-container .btn {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a red background color to the cancel button */\r\n");
      out.write(".form-container .cancel {\r\n");
      out.write("  background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add some hover effects to buttons */\r\n");
      out.write(".form-container .btn:hover,\r\n");
      out.write(".open-button:hover {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form-popup-delete {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 30px; /* Added 'px' unit */\r\n");
      out.write("  right: 30px; /* Changed to 'right' and adjusted distance */\r\n");
      out.write("  border: 3px solid #f1f1f1;\r\n");
      out.write("  z-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container-delete {\r\n");
      out.write("  max-width: 400px;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write(".form-container-delete input[type=text] {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 5px 0 22px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* When the inputs get focus, do something */\r\n");
      out.write(".form-container-delete input[type=text]:focus{\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit*/\r\n");
      out.write(".form-container-delete .btn {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom:10px;\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a red background color to the cancel button */\r\n");
      out.write(".form-container-delete .cancel {\r\n");
      out.write("  background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add some hover effects to buttons */\r\n");
      out.write(".form-container-delete .btn:hover, .open-button:hover {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-enter {\r\n");
      out.write("    width: 50%; /* Set the width of the container */\r\n");
      out.write("    margin: 0 auto; /* Center the container horizontally */\r\n");
      out.write("    height: 150px; /* Set the height of the division */\r\n");
      out.write("    overflow-y: auto; /* Add vertical scrollbar if content exceeds the height */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".update-enter h2 {\r\n");
      out.write("    text-align: center; /* Center the heading */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-enter form {\r\n");
      out.write("    width: 50%; /* Set the width of the form to 100% of the container */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-enter label,\r\n");
      out.write(".update-enter input,\r\n");
      out.write(".update-enter button {\r\n");
      out.write("    display: block; /* Display form elements as block-level to stack them vertically */\r\n");
      out.write("    width: 80%; /* Set the width of form elements to 100% */\r\n");
      out.write("    margin-bottom: -2px; /* Add some vertical spacing between elements */\r\n");
      out.write("}\r\n");
      out.write(".update-enter-delete {\r\n");
      out.write("    width: 80%; /* Set the width of the container */\r\n");
      out.write("    margin: 0 auto; /* Center the container horizontally */\r\n");
      out.write("    position: absolute; /* Position the division absolutely */\r\n");
      out.write("    bottom: 0; /* Align the division to the bottom of the page */\r\n");
      out.write("    left: 50%; /* Center the division horizontally */\r\n");
      out.write("    transform: translateX(-50%); /* Center the division horizontally */\r\n");
      out.write("    height: 400px; /* Set the height of the division */\r\n");
      out.write("    overflow-y: auto; /* Add vertical scrollbar if content exceeds the height */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section id=\"sidebar\">\r\n");
      out.write("		<a href=\"#\" class=\"brand\">\r\n");
      out.write("			\r\n");
      out.write("			<span class=\"text\">Admin</span>\r\n");
      out.write("		</a>\r\n");
      out.write("		<ul class=\"side-menu top\">\r\n");
      out.write("			<li class=\"active\">\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class='bx bxs-dashboard' ></i>\r\n");
      out.write("					<span class=\"text\">Dashboard</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class='bx bxs-shopping-bag-alt' ></i>\r\n");
      out.write("					<span class=\"text\">My Store</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class='bx bxs-doughnut-chart' ></i>\r\n");
      out.write("					<span class=\"text\">Analytics</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class='bx bxs-message-dots' ></i>\r\n");
      out.write("					<span class=\"text\">Messages</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class='bx bxs-group' ></i>\r\n");
      out.write("					<span class=\"text\">Our Team</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<ul class=\"side-menu\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class='bx bxs-cog' ></i>\r\n");
      out.write("					<span class=\"text\">Settings</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"#\" class=\"logout\">\r\n");
      out.write("					<i class='bx bxs-log-out-circle' ></i>\r\n");
      out.write("					<span class=\"text\">Logout</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section id=\"content\">\r\n");
      out.write("		\r\n");
      out.write("		<nav>\r\n");
      out.write("			<i class='bx bx-menu' ></i>\r\n");
      out.write("			<form action=\"#\">\r\n");
      out.write("				<div class=\"form-input\">\r\n");
      out.write("					<input type=\"search\" placeholder=\"Search...\">\r\n");
      out.write("					<button type=\"submit\" class=\"search-btn\"><i class='bx bx-search' ></i></button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<input type=\"checkbox\" id=\"switch-mode\" hidden>\r\n");
      out.write("			<label for=\"switch-mode\" class=\"switch-mode\"></label>\r\n");
      out.write("			<a href=\"#\" class=\"notification\">\r\n");
      out.write("				<i class='bx bxs-bell' ></i>\r\n");
      out.write("				<span class=\"num\">8</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<a href=\"#\" class=\"profile\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</nav>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<main>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("    <h2 class=\"heading\">Change User Details</h2>\r\n");
      out.write("</div>\r\n");
      out.write("		\r\n");
      out.write("<div class=\"table-data\">\r\n");
      out.write("				<div class=\"order\">\r\n");
      out.write("					<div class=\"head\">\r\n");
      out.write("					<h3>Do You Want To view Customer Details </h3>\r\n");
      out.write("						\r\n");
      out.write("						<i class='bx bx-search' onclick=\"openForm()\"></i>\r\n");
      out.write("							<div class=\"form-popup\" id=\"myForm\" >\r\n");
      out.write("  						<form action=\"userView\" class=\"form-container\" method=\"post\">\r\n");
      out.write("  							<h2 style=\"color: #333; font-size: 24px;\">View User Details</h2>\r\n");
      out.write("   							<label for=\"text\"><b>User Name:</b></label>\r\n");
      out.write("    						<input type=\"text\" placeholder=\"Enter username\" name=\"uid\" required>\r\n");
      out.write("\r\n");
      out.write("    						<button type=\"submit\" class=\"btn\">View</button>\r\n");
      out.write("    						<button type=\"button\" class=\"btn cancel\" onclick=\"closeForm()\">Close</button>\r\n");
      out.write("  					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<i class='bx bx-filter' ></i>\r\n");
      out.write("						</div>\r\n");
      out.write("				\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"output-table-container\">\r\n");
      out.write("       <table>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       	\r\n");
      out.write("       <div class=\"update-enter\">\r\n");
      out.write("		\r\n");
      out.write("				<div class=\"head\">\r\n");
      out.write("						<h3>Do You Want To Remove The User </h3>\r\n");
      out.write("						<i class='bx bx-search' onclick=\"openFormDelete()\"></i>\r\n");
      out.write("						<i class='bx bx-filter' ></i>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>					\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"form-popup-delete\" id=\"myFormdelete\">\r\n");
      out.write("  		  <form action=\"/action_page.php\" class=\"form-container-delete\" method=\"post\">\r\n");
      out.write("   			<h2 style=\"color: #333; font-size: 24px;\">Delete User</h2>\r\n");
      out.write("   			 <label for=\"text\"><b>UserId:</b></label>\r\n");
      out.write("   			 <input type=\"text\" placeholder=\"Enter busid\" name=\"busid\" required>\r\n");
      out.write("    		 <button type=\"submit\" class=\"btn\">Delete </button>\r\n");
      out.write("             <button type=\"button\" class=\"btn cancel\" onclick=\"closeFormDelete()\">Cancel</button>\r\n");
      out.write("         </form>\r\n");
      out.write("	</div>					\r\n");
      out.write("	\r\n");
      out.write("	</main>	\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function openForm() {\r\n");
      out.write("  document.getElementById(\"myForm\").style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeForm() {\r\n");
      out.write("  document.getElementById(\"myForm\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openFormDelete() {\r\n");
      out.write("	  document.getElementById(\"myFormdelete\").style.display = \"block\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function closeFormDelete() {\r\n");
      out.write("	  document.getElementById(\"myFormdelete\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /view.jsp(729,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cus");
      // /view.jsp(729,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view.jsp(729,12) '${cusDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cusDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>Customer ID:</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.cusid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>First Name:</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>Last Name:</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.lname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>Email Address:</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>Address</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>Contact No.:</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                <tr>\r\n");
            out.write("                    <td>User Name:</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
